# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class YabaiWrapper < Formula
  desc "Wrapper for yabai window manager"
  homepage "https://github.com/williampayne23/Yabai_Wrapper"
  url "https://github.com/williampayne23/Yabai_Wrapper/archive/v1.4.8.tar.gz"
  sha256 "e528f4c9c3ff83864e662459dfcbc715a7c6e793e0b51c1b881ae5cb2fba6766"
  license "GPL-2.0"
  bottle :unneeded

  def install
    libexec.install "src/yabai_wrapper.sh" => "yabai_wrapper" and libexec.install Dir["src/*"] and bin.write_exec_script (libexec/"yabai_wrapper")
  end
end
