# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class YabaiWrapper < Formula
  desc "Wrapper for yabai window manager"
  homepage "https://github.com/williampayne23/Yabai_Wrapper"
  url "https://github.com/williampayne23/Yabai_Wrapper/archive/Fixed action issue.tar.gz"
  sha256 "d5558cd419c8d46bdc958064cb97f963d1ea793866414c025906ec15033512ed"
  license "GPL-2.0"
  bottle :unneeded

  def install
    libexec.install "src/yabai_wrapper.sh" => "yabai_wrapper" 
    libexec.install Dir["src/*"] 
    bin.write_exec_script (libexec/"yabai_wrapper")
  end
end
