# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class YabaiWrapper < Formula
  desc "Wrapper for yabai window manager"
  homepage "https://github.com/williampayne23/Yabai_Wrapper"
  url "https://github.com/williampayne23/Yabai_Wrapper/archive/v1.5.2.tar.gz"
  sha256 "8d951636255b959b1da62014c84928c1704811b30ef11f5f56f45648279775b8"
  license "GPL-2.0"
  bottle :unneeded

  def install
    libexec.install "src/yabai_wrapper.sh" => "yabai_wrapper" and libexec.install Dir["src/*"] and bin.write_exec_script (libexec/"yabai_wrapper")
  end
end
